// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.demo.grpc;

public interface CreateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 1;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string roomType = 2;</code>
   * @return The roomType.
   */
  java.lang.String getRoomType();
  /**
   * <code>string roomType = 2;</code>
   * @return The bytes for roomType.
   */
  com.google.protobuf.ByteString
      getRoomTypeBytes();

  /**
   * <code>string startDate = 3;</code>
   * @return The startDate.
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 3;</code>
   * @return The bytes for startDate.
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string endDate = 4;</code>
   * @return The endDate.
   */
  java.lang.String getEndDate();
  /**
   * <code>string endDate = 4;</code>
   * @return The bytes for endDate.
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
