// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.demo.grpc;

public interface GetReservationByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
