// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.demo.grpc;

public interface GetReservationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationsRequest)
    com.google.protobuf.MessageOrBuilder {
}
