// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.demo.grpc;

public interface GetReservationByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.example.demo.grpc.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  com.example.demo.grpc.ReservationOrBuilder getReservationOrBuilder();
}
