// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.demo.grpc;

public final class ReservationServiceProto {
  private ReservationServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\"\'\n\031GetReservationByI" +
      "dRequest\022\n\n\002id\030\001 \001(\003\"?\n\032GetReservationBy" +
      "IdResponse\022!\n\013reservation\030\001 \001(\0132\014.Reserv" +
      "ation\"\030\n\026GetReservationsRequest\"=\n\027GetRe" +
      "servationsResponse\022\"\n\014reservations\030\001 \003(\013" +
      "2\014.Reservation\"d\n\030CreateReservationReque" +
      "st\022\022\n\nclientName\030\001 \001(\t\022\020\n\010roomType\030\002 \001(\t" +
      "\022\021\n\tstartDate\030\003 \001(\t\022\017\n\007endDate\030\004 \001(\t\">\n\031" +
      "CreateReservationResponse\022!\n\013reservation" +
      "\030\001 \001(\0132\014.Reservation\"&\n\030DeleteReservatio" +
      "nRequest\022\n\n\002id\030\001 \001(\003\",\n\031DeleteReservatio" +
      "nResponse\022\017\n\007success\030\001 \001(\010\"c\n\013Reservatio" +
      "n\022\n\n\002id\030\001 \001(\003\022\022\n\nclientName\030\002 \001(\t\022\020\n\010roo" +
      "mType\030\003 \001(\t\022\021\n\tstartDate\030\004 \001(\t\022\017\n\007endDat" +
      "e\030\005 \001(\t2\301\002\n\022ReservationService\022M\n\022GetRes" +
      "ervationById\022\032.GetReservationByIdRequest" +
      "\032\033.GetReservationByIdResponse\022D\n\017GetRese" +
      "rvations\022\027.GetReservationsRequest\032\030.GetR" +
      "eservationsResponse\022J\n\021CreateReservation" +
      "\022\031.CreateReservationRequest\032\032.CreateRese" +
      "rvationResponse\022J\n\021DeleteReservation\022\031.D" +
      "eleteReservationRequest\032\032.DeleteReservat" +
      "ionResponseB2\n\025com.example.demo.grpcB\027Re" +
      "servationServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetReservationByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_GetReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationRequest_descriptor,
        new java.lang.String[] { "ClientName", "RoomType", "StartDate", "EndDate", });
    internal_static_CreateReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CreateReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "ClientName", "RoomType", "StartDate", "EndDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
