// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.demo.grpc;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string clientName = 2;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 2;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string roomType = 3;</code>
   * @return The roomType.
   */
  java.lang.String getRoomType();
  /**
   * <code>string roomType = 3;</code>
   * @return The bytes for roomType.
   */
  com.google.protobuf.ByteString
      getRoomTypeBytes();

  /**
   * <code>string startDate = 4;</code>
   * @return The startDate.
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 4;</code>
   * @return The bytes for startDate.
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string endDate = 5;</code>
   * @return The endDate.
   */
  java.lang.String getEndDate();
  /**
   * <code>string endDate = 5;</code>
   * @return The bytes for endDate.
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
