global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'       # Spring Boot metrics endpoint
    static_configs:
      - targets: ['host.docker.internal:8080']  # Replace with your app's address
  - job_name: 'jmeter'
    static_configs:
      - targets: ['localhost:9270']